Section "Device"
  Identifier "AMDGPU"
  Driver "amdgpu"
  Option "TearFree" "true"
EndSection

Section "Screen"
  Identifier "Screen0"
  Device "AMDGPU"
EndSection

Section "ServerFlags"
  Option "DontVTSwitch" "false"
  Option "AllowMouseOpenFail" "true"
EndSection
