name = "pallet-os-server"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_USERNAME = "admin"
# Override in Cloudflare dashboard or wrangler secret put ADMIN_PASSWORD
JWT_ISSUER = "pallet-os"

[[d1_databases]]
binding = "DB"
database_name = "pallet-os"
database_id = "ec24a1e0-e4c1-48ec-beee-c9234f9ecbea"

[observability]
enabled = true
